import pandas as pd
import os

# Paths
KMEANS_RESULTS = r"c:\Projects\Stroke-awareness-TY-mini-project\models\clustering_v2\kmeans_results.csv"
REPORT_PATH = r"c:\Projects\Stroke-awareness-TY-mini-project\models\clustering_v2\cluster_verification_report.md"

def run_analysis():
    if not os.path.exists(KMEANS_RESULTS):
        print(f"Error: {KMEANS_RESULTS} not found.")
        return

    df = pd.read_csv(KMEANS_RESULTS)

    # 1. Verify Cluster Identity Features
    # Identify feature columns (z-scaled) as done in clustering_kmeans.py
    features_z = [c for c in df.columns if c.startswith('z_')]
    original_features = [f.replace('z_', '') for f in features_z]
    
    print("-" * 60)
    print("VERIFICATION: CLUSTER IDENTITY")
    print("-" * 60)
    print(f"Features used for clustering (z-scaled): {features_z}")
    
    is_cat_used = "awareness_cat" in original_features or "z_awareness_cat" in df.columns
    print(f"Is 'awareness_category' used for cluster identity? {'YES' if is_cat_used else 'NO'}")
    print("-" * 60)

    # 2. Compute Mean Metrics per Cluster
    # Mapping columns as requested
    # awareness_score -> awareness_score
    # lifestyle_risk_score -> lifestyle_risk_score
    # urgency -> score_urgency
    # action -> score_action_first_symptom
    
    metrics = {
        'awareness_score': 'Mean Awareness Score',
        'lifestyle_risk_score': 'Mean Lifestyle Risk Score',
        'score_urgency': 'Mean Urgency',
        'score_action_first_symptom': 'Mean Action'
    }

    cluster_means = df.groupby('cluster_kmeans')[list(metrics.keys())].mean()
    cluster_means.columns = [metrics[c] for c in cluster_means.columns]

    # 3. Awareness Category Distribution
    # % of individuals classified as high awareness, moderate awareness and low awareness
    cat_dist = df.groupby(['cluster_kmeans', 'awareness_cat']).size().unstack(fill_value=0)
    cat_dist_pct = cat_dist.div(cat_dist.sum(axis=1), axis=0) * 100

    # 4. Age Distribution
    age_dist = df.groupby(['cluster_kmeans', 'age_group_4cat']).size().unstack(fill_value=0)
    age_dist_pct = age_dist.div(age_dist.sum(axis=1), axis=0) * 100

    # 5. Cluster Size Diagnostics (NEW)
    cluster_counts = df['cluster_kmeans'].value_counts().sort_index()
    cluster_percent = (cluster_counts / len(df)) * 100
    cluster_summary = pd.DataFrame({
        'Count': cluster_counts,
        'Percentage (%)': cluster_percent.round(2)
    })

    # --- Generate Report ---
    report = []
    report.append("# Cluster Verification & Profiling Report (REFINED)\n")
    
    report.append("## 1. Feature Audit (Cluster Identity)")
    report.append(f"Confirmed that **`awareness_cat`** and **`symptom_awareness_score`** are **NOT** used for cluster identity.")
    report.append("The clustering algorithm utilized the following 5 z-scaled features:")
    for f in features_z:
        report.append(f"- {f}")
    report.append("\n")

    report.append("## 2. Cluster Size Summary")
    report.append("```\n" + cluster_summary.to_string() + "\n```")
    report.append("\n")

    report.append("## 3. Cluster Profiles (Mean Metrics)")
    report.append("```\n" + cluster_means.to_string() + "\n```")
    report.append("\n")

    report.append("## 4. Awareness Category Distribution (%)")
    report.append("```\n" + cat_dist_pct.to_string() + "\n```")
    report.append("\n")

    report.append("## 5. Age Distribution (%)")
    report.append("```\n" + age_dist_pct.to_string() + "\n```")
    report.append("\n")


    report.append("---")
    report.append("*Generated by Cluster Verification Analysis Tool*")

    with open(REPORT_PATH, "w") as f:
        f.write("\n".join(report))

    print(f"Analysis complete. Report saved to: {REPORT_PATH}")
    print("\nCluster Mean Summary:")
    print(cluster_means)
    print("\nAwareness Category %:")
    print(cat_dist_pct)

if __name__ == "__main__":
    run_analysis()
